### ISSUE TITLE
 Module build failed after update to 2.0.1 

### ISSUE THREAD

**Issue by nejc-susin** [wxsms/vue-md-loader#348]
Hi,
I am getting the below error on 2.0.1, but not on 2.0.0. 
```
Error: Module build failed (from ./node_modules/vue-md-loader/index.js):
TypeError: this.getOptions is not a function
    at Object.module.exports (E:\git\project\node_modules\vue-md-loader\index.js:7:24)
    at eval (webpack-internal:///./src/assets/markdown.md:1:7)
    at Object../src/assets/markdown.md (https://localhost/js/app.js:5881:1)
    at __webpack_require__ (https://localhost/js/app.js:854:30)
    at fn (https://localhost/js/app.js:151:20)
    at VueComponent.created 
    ...
```

I could be totally wrong, but looking at the source and what changed, I would guess that `loader-utils` should not have been removed like they were in 59ae702. The [v3 way](https://github.com/webpack/loader-utils/releases/tag/v3.0.0) of calling `getOptions()` makes it seem like we don't need the dependency but I guess we do.

Downgrading fixes it for me, but I thought it was worth pointing out anyway.

**Comment by wxsms** [comment]
Hello. Thanks for report. I guess this is a mistake, if you're using webpack v5, this should not happen. I just updated the [release note](https://github.com/wxsms/vue-md-loader/releases/tag/v2.0.0) to point this out. If you still need webpack v4 or lower, pls use 1.x of this plugin. Thanks.

If you are using webpack v5 then this issue happens, pls let me know. We can continue on this topic.

**Comment by nejc-susin** [comment]
That makes sense. I cannot go into webpack upgrade at the moment, so I'll stay on the old version. Thanks for clearing it up!

**Comment by wxsms** [comment]
Welcome.
